---
deployment:
    tasks:
        - export REPOPATH=/home/rdnby/repositories/rdn3/*
        - export SITEPATH=/home/rdnby/rdn.by/
        - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
